apiVersion: v2
appVersion: "3.2.0"
description: A Helm chart for Ackee analytics tool
name: ackee
version: 0.2.2-rc0
type: application
kubeVersion: ^1.19.0
sources:
  - https://github.com/suda/charts/tree/main/charts/ackee
home: https://github.com/suda/charts/tree/main/charts/ackee
maintainers:
  - name: suda
    email: admin@suda.pl
    url: https://suda.pl
